# -*- coding: utf-8 -*-
"""machine.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwh8ml4t5syjQb1bJpkClHzeEDTQ_qfC
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv('SwedishMotorInsurance.csv')

dataset

dataset=dataset[["Kilometres","Zone","Make","Insured","Claims","Payment"]]

dataset

dataset.corr()["Payment"]

import seaborn as sns

sns.lmplot(x="Insured",y="Payment",data=dataset,fit_reg=True,ci=None)

sns.lmplot(x="Make",y="Payment",data=dataset,fit_reg=True,ci=None)

sns.lmplot(x="Claims",y="Payment",data=dataset,fit_reg=True,ci=None)

dataset.plot.hist (y="Payment")

dataset[dataset.isnull().any(axis=1)]

dataset = dataset.dropna()

train =dataset[dataset["Payment"] <119373].copy()
test =dataset[dataset["Payment"] >=119373].copy()

train.shape

test.shape

from sklearn.linear_model import LinearRegression

reg= LinearRegression()

predictors =["Claims","Make","Insured"]
target ="Payment"

reg.fit(train[predictors],train["Payment"])

predictions =reg.predict(test[predictors])

predictions

dataset.describe()["Payment"]

test["predictions"] =predictions

test

test.loc[test["predictions"] <0,"predictions"] =0

test["predictions"] =test["predictions"].round()

test

from sklearn.metrics import mean_absolute_error

error =mean_absolute_error(test["Payment"], test["predictions"])

error

dataset.describe() ["Payment"]

